const $=s=>document.querySelector(s); const modal=$('#modal'), body=$('#dialogBody');
let token=localStorage.getItem('pm_token');
const cats=['Polovni automobili','Nekretnine','Mobilni telefoni','Tehnika','Usluge','Građevina','Poljoprivreda','Moda','Ostalo'];
$('#categories').innerHTML=cats.map((c,i)=>`<button class="cat" onclick="setCat('${c}')"><b>${['🚗','🏠','📱','💻','🛠️','👷','🚜','👕','•••'][i]} ${c}</b><small>${[12580,23120,15890,9452,18760,8542,7310,4125,0][i].toLocaleString('sr-RS')} oglasa</small></button>`).join('');
$('#category').innerHTML='<option value="">Sve kategorije</option>'+cats.map(c=>`<option>${c}</option>`).join('');
function setCat(c){$('#category').value=c; doSearch()}
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Greška');return d}
async function doSearch(){const q=$('#q').value,category=$('#category').value,location=$('#location').value;const data=await api(`/api/listings?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&location=${encodeURIComponent(location)}`);$('#featured').innerHTML=data.length?data.slice(0,3).map(x=>`<div class="offer"><img src="${x.image}"><div><b>${x.title}</b><br><small>${x.location} • ${x.price?new Intl.NumberFormat('sr-RS').format(x.price)+' €':'Po dogovoru'}</small></div></div>`).join(''):'Nema rezultata.'}
$('#searchBtn').onclick=doSearch; doSearch();
function openModal(html){body.innerHTML=html;modal.classList.remove('hidden')}; $('#close').onclick=()=>modal.classList.add('hidden'); modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
function register(){openModal(`<h2>Registracija</h2><div class="tabs"><button class="active" id="ind">Fizičko lice</button><button id="firm">Pravno lice</button></div><form id="reg"><input name="name" placeholder="Ime i prezime" required><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Lozinka" required><div id="companyFields"></div><button class="submit">Kreiraj nalog</button></form>`);let type='individual';$('#ind').onclick=()=>{type='individual';$('#ind').classList.add('active');$('#firm').classList.remove('active');$('#companyFields').innerHTML=''};$('#firm').onclick=()=>{type='company';$('#firm').classList.add('active');$('#ind').classList.remove('active');$('#companyFields').innerHTML='<input name="companyName" placeholder="Naziv firme" required><input name="pib" placeholder="PIB">'};$('#reg').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),x=Object.fromEntries(f);try{const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify({...x,type})});token=d.token;localStorage.setItem('pm_token',token);alert('Registracija je uspešna.');modal.classList.add('hidden')}catch(err){alert(err.message)}}}
function login(){openModal(`<h2>Prijava</h2><form id="login"><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Lozinka" required><button class="submit">Prijavi se</button></form>`);$('#login').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.target));try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify(x)});token=d.token;localStorage.setItem('pm_token',token);alert('Uspešna prijava.');modal.classList.add('hidden')}catch(err){alert(err.message)}}}
function requireAuth(action){if(!token){alert('Za ovu opciju potrebna je prijava.');login();return false}return true}
function listing(){if(!requireAuth())return;openModal(`<h2>Objavi oglas</h2><form id="listing"><input name="title" placeholder="Naslov oglasa" required><select name="category">${cats.map(c=>`<option>${c}</option>`).join('')}</select><input name="location" placeholder="Lokacija" required><input name="price" type="number" placeholder="Cena (€)"><textarea name="description" placeholder="Opis"></textarea><button class="submit">Objavi</button></form>`);$('#listing').onsubmit=async e=>{e.preventDefault();try{await api('/api/listings',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert('Oglas je objavljen.');modal.classList.add('hidden');doSearch()}catch(err){alert(err.message)}}}
function request(){if(!requireAuth())return;openModal(`<h2>Postavi zahtev</h2><form id="request"><input name="title" placeholder="Šta tražite?" required><select name="category"><option value="">Kategorija</option>${cats.map(c=>`<option>${c}</option>`).join('')}</select><input name="location" placeholder="Lokacija"><input name="budget" type="number" placeholder="Budžet (€)"><textarea name="description" placeholder="Opišite šta vam je potrebno"></textarea><button class="submit">Pošalji zahtev</button></form>`);$('#request').onsubmit=async e=>{e.preventDefault();try{await api('/api/requests',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert('Zahtev je sačuvan.');modal.classList.add('hidden')}catch(err){alert(err.message)}}}
function support(){openModal(`<h2>Centar za podršku</h2><div class="tabs"><button class="active" id="chatTab">PonudiMi Asistent</button><button id="faqTab">Najčešća pitanja</button><button id="ticketTab">Pošalji upit</button></div><div id="supportArea"></div>`);showChat();$('#chatTab').onclick=showChat;$('#faqTab').onclick=showFaq;$('#ticketTab').onclick=showTicket}
function showChat(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));$('#chatTab').classList.add('active');$('#supportArea').innerHTML=`<div class="notice">Asistent je trenutno podešen za pitanja o PonudiMi platformi: registracija, prijava, oglasi, zahtevi i paketi.</div><div class="chat" id="chat"><div class="msg bot">Zdravo! Kako mogu da pomognem?</div></div><div class="chatrow"><input id="chatInput" placeholder="Napišite pitanje..."><button class="submit" id="send">Pošalji</button></div>`;$('#send').onclick=sendChat;$('#chatInput').onkeydown=e=>{if(e.key==='Enter')sendChat()}}
async function sendChat(){const input=$('#chatInput');if(!input.value.trim())return;const chat=$('#chat'),m=input.value;chat.innerHTML+=`<div class="msg me">${escapeHtml(m)}</div>`;input.value='';const d=await api('/api/support/chat',{method:'POST',body:JSON.stringify({message:m})});chat.innerHTML+=`<div class="msg bot">${escapeHtml(d.answer)}</div>`;chat.scrollTop=chat.scrollHeight}
function showFaq(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));$('#faqTab').classList.add('active');$('#supportArea').innerHTML=`<div class="faq">${['Kako da se registrujem kao fizičko lice?','Kako da registrujem firmu?','Kako da se prijavim?','Kako da objavim oglas?','Kako da postavim zahtev?','Kako rade paketi za firme?'].map(q=>`<button onclick="faqAsk('${q}')">${q}</button>`).join('')}</div>`}
async function faqAsk(q){const d=await api('/api/support/chat',{method:'POST',body:JSON.stringify({message:q})});alert(d.answer)}
function showTicket(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.remove('active'));$('#ticketTab').classList.add('active');$('#supportArea').innerHTML=`<form id="ticket"><input name="name" placeholder="Ime i prezime" required><input name="email" type="email" placeholder="Email" required><input name="subject" placeholder="Naslov upita" required><textarea name="message" placeholder="Opišite problem ili pitanje" required></textarea><button class="submit">Pošalji upit</button></form>`;$('#ticket').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/support/tickets',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert(d.message);modal.classList.add('hidden')}catch(err){alert(err.message)}}}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
$('#supportBtn').onclick=support;$('#loginBtn').onclick=login;$('#registerBtn').onclick=register;$('#ctaRegister').onclick=register;$('#listingBtn').onclick=listing;$('#requestBtn').onclick=request;
